#!/bin/bash

sm -f --start DATASTREAM AUTH AUTH_LOGIN_API AUTH_LOGIN_STUB ASSETS_FRONTEND TIME_BASED_ONE_TIME_PASSWORD STRIDE_AUTH_FRONTEND STRIDE_AUTH STRIDE_IDP_STUB API_PUBLISHER USER_DETAILS

sm --start API_GATEWAY_STUB THIRD_PARTY_APPLICATION THIRD_PARTY_DEVELOPER API_DEFINITION API_SCOPE

./run_local.sh
