#!/bin/bash

sm -f --start MONGO DATASTREAM AUTH AUTH_LOGIN_API AUTH_LOGIN_STUB ASSETS_FRONTEND 

sm --start API_GATEWAY_STUB THIRD_PARTY_APPLICATION THIRD_PARTY_DEVELOPER API_DEFINITION API_SCOPE

./run_local.sh
