#!/bin/bash

sm --start ASSETS_FRONTEND -r 3.12.0

sm --start DATASTREAM  AUTH_LOGIN_API AUTH_LOGIN_STUB TIME_BASED_ONE_TIME_PASSWORD STRIDE_AUTH_FRONTEND STRIDE_AUTH STRIDE_IDP_STUB API_PUBLISHER USER_DETAILS

sm --start API_GATEWAY_STUB THIRD_PARTY_DEVELOPER API_DEFINITION API_SUBSCRIPTION_FIELDS API_PLATFORM_EVENTS

./run_local.sh
